// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoClub.Api.Data;

#nullable disable

namespace VideoClub.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609011437_RenameRentaDevolucionToRentas")]
    partial class RenameRentaDevolucionToRentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Articulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DiasRenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<long>("GeneroId")
                        .HasColumnType("bigint");

                    b.Property<long>("IdiomaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MontoEntregaTardia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RentaPorDia")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("renta_por_dia");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("TipoArticuloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("TipoArticuloId");

                    b.ToTable("Articulos", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<decimal>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("NoTarjetaCr")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("no_tarjeta_cr");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_NoTarjetaCr", "no_tarjeta_cr ~ '^[0-9]{4}$'");
                        });
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Elenco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.ToTable("Elenco", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.ElencoArticulo", b =>
                {
                    b.Property<long>("ArticuloId")
                        .HasColumnType("bigint");

                    b.Property<long>("ElencoId")
                        .HasColumnType("bigint");

                    b.Property<long>("RolElencoId")
                        .HasColumnType("bigint");

                    b.HasKey("ArticuloId", "ElencoId", "RolElencoId");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ElencoId");

                    b.HasIndex("RolElencoId");

                    b.ToTable("ElencoArticulo", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Empleado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<decimal>("PorcientoComision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TandaLabor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tanda_labor");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Empleados", null, t =>
                        {
                            t.HasCheckConstraint("CK_Empleados_TandaLabor", "tanda_labor IN ('Matutina', 'Vespertina')");
                        });
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Genero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Idioma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.ToTable("Idiomas", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Renta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<long>("EmpleadoId")
                        .HasColumnType("bigint");

                    b.Property<string>("EstadoRenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaDevolucionReal")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("FechaExpectedDevolucion")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("FechaRenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("MontoRetraso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NoRenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("NoRenta")
                        .IsUnique();

                    b.HasIndex("ClienteId", "FechaRenta")
                        .IsDescending(false, true);

                    b.HasIndex("EstadoRenta", "FechaRenta")
                        .IsDescending(false, true);

                    b.ToTable("Rentas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rentas_EstadoRenta", "\"EstadoRenta\" IN ('Activa', 'Devuelta')");

                            t.HasCheckConstraint("CK_Rentas_FechaExpected", "\"FechaExpectedDevolucion\" > \"FechaRenta\"");

                            t.HasCheckConstraint("CK_Rentas_FechaReal", "\"FechaDevolucionReal\" IS NULL OR \"FechaDevolucionReal\" >= \"FechaRenta\"");

                            t.HasCheckConstraint("CK_Rentas_MontoRetraso", "\"MontoRetraso\" >= 0.0");
                        });
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.RentaDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticuloId")
                        .HasColumnType("bigint");

                    b.Property<int>("CantidadDias")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<int>("DiasRetraso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaDevolucionEsperada")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("FechaDevolucionReal")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("MontoPorDia")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MontoRetraso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("MontoTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(10,2)")
                        .HasComputedColumnSql("\"MontoPorDia\" * \"CantidadDias\"", true);

                    b.Property<long>("RentaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("RentaId");

                    b.ToTable("RentaDetalles", null, t =>
                        {
                            t.HasCheckConstraint("CK_RentaDetalles_CantidadDias", "\"CantidadDias\" > 0");

                            t.HasCheckConstraint("CK_RentaDetalles_DiasRetraso", "\"DiasRetraso\" >= 0");

                            t.HasCheckConstraint("CK_RentaDetalles_MontoPorDia", "\"MontoPorDia\" > 0");

                            t.HasCheckConstraint("CK_RentaDetalles_MontoRetraso", "\"MontoRetraso\" >= 0.0");
                        });
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.RolElenco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.ToTable("RolesElenco", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.TipoArticulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.ToTable("TiposArticulos", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.TipoArticuloGenero", b =>
                {
                    b.Property<long>("TipoArticuloId")
                        .HasColumnType("bigint");

                    b.Property<long>("GeneroId")
                        .HasColumnType("bigint");

                    b.HasKey("TipoArticuloId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("TipoArticuloId");

                    b.ToTable("TiposArticulosGeneros", (string)null);
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Articulo", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Genero", "Genero")
                        .WithMany("Articulos")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Idioma", "Idioma")
                        .WithMany("Articulos")
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("Articulos")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Idioma");

                    b.Navigation("TipoArticulo");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.ElencoArticulo", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Articulo", "Articulo")
                        .WithMany("Elencos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Elenco", "Elenco")
                        .WithMany("Articulos")
                        .HasForeignKey("ElencoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.RolElenco", "RolElenco")
                        .WithMany("ElencosArticulos")
                        .HasForeignKey("RolElencoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Elenco");

                    b.Navigation("RolElenco");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Renta", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Cliente", "Cliente")
                        .WithMany("Rentas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Empleado", "Empleado")
                        .WithMany("Rentas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.RentaDetalle", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Articulo", "Articulo")
                        .WithMany("RentaDetalles")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.Renta", "Renta")
                        .WithMany("Detalles")
                        .HasForeignKey("RentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Renta");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.TipoArticuloGenero", b =>
                {
                    b.HasOne("VideoClub.Api.Data.Entities.Genero", "Genero")
                        .WithMany("TiposArticulosGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoClub.Api.Data.Entities.TipoArticulo", "TipoArticulo")
                        .WithMany("TiposArticulosGeneros")
                        .HasForeignKey("TipoArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("TipoArticulo");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Articulo", b =>
                {
                    b.Navigation("Elencos");

                    b.Navigation("RentaDetalles");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Cliente", b =>
                {
                    b.Navigation("Rentas");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Elenco", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Empleado", b =>
                {
                    b.Navigation("Rentas");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Genero", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("TiposArticulosGeneros");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Idioma", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.Renta", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.RolElenco", b =>
                {
                    b.Navigation("ElencosArticulos");
                });

            modelBuilder.Entity("VideoClub.Api.Data.Entities.TipoArticulo", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("TiposArticulosGeneros");
                });
#pragma warning restore 612, 618
        }
    }
}
