CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "Clientes" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Cedula" text NOT NULL,
        no_tarjeta_cr char(4) NOT NULL,
        "LimiteCredito" numeric(10,2) NOT NULL DEFAULT 0.0,
        "TipoPersona" text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Clientes_NoTarjetaCr" CHECK (no_tarjeta_cr ~ '^[0-9]{4}$')
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "Elenco" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Elenco" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "Empleados" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Cedula" text NOT NULL,
        tanda_labor text NOT NULL,
        "PorcientoComision" numeric(5,2) NOT NULL DEFAULT 0.0,
        "FechaIngreso" date NOT NULL,
        nombre_usuario text NOT NULL,
        password_hash text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Empleados" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Empleados_TandaLabor" CHECK (tanda_labor IN ('Matutina', 'Vespertina'))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "Generos" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Descripcion" text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Generos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "Idiomas" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Descripcion" text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Idiomas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "RolesElenco" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Descripcion" text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_RolesElenco" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "TiposArticulos" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Descripcion" text NOT NULL,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_TiposArticulos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "Articulos" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Titulo" text NOT NULL,
        "TipoArticuloId" bigint NOT NULL,
        "GeneroId" bigint NOT NULL,
        "IdiomaId" bigint NOT NULL,
        renta_por_dia numeric(10,2) NOT NULL,
        "DiasRenta" integer NOT NULL DEFAULT 3,
        "MontoEntregaTardia" numeric(10,2) NOT NULL DEFAULT 0.0,
        "Stock" integer NOT NULL DEFAULT 0,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_Articulos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Articulos_Generos_GeneroId" FOREIGN KEY ("GeneroId") REFERENCES "Generos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Articulos_Idiomas_IdiomaId" FOREIGN KEY ("IdiomaId") REFERENCES "Idiomas" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Articulos_TiposArticulos_TipoArticuloId" FOREIGN KEY ("TipoArticuloId") REFERENCES "TiposArticulos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "ElencoArticulo" (
        "ArticuloId" bigint NOT NULL,
        "ElencoId" bigint NOT NULL,
        "RolElencoId" bigint NOT NULL,
        CONSTRAINT "PK_ElencoArticulo" PRIMARY KEY ("ArticuloId", "ElencoId", "RolElencoId"),
        CONSTRAINT "FK_ElencoArticulo_Articulos_ArticuloId" FOREIGN KEY ("ArticuloId") REFERENCES "Articulos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ElencoArticulo_Elenco_ElencoId" FOREIGN KEY ("ElencoId") REFERENCES "Elenco" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ElencoArticulo_RolesElenco_RolElencoId" FOREIGN KEY ("RolElencoId") REFERENCES "RolesElenco" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE TABLE "RentaDevolucion" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "NoRenta" text NOT NULL,
        "EmpleadoId" bigint NOT NULL,
        "ArticuloId" bigint NOT NULL,
        "ClienteId" bigint NOT NULL,
        fecha_renta timestamptz NOT NULL DEFAULT (now()),
        fecha_devolucion timestamptz,
        "MontoXdia" numeric(10,2) NOT NULL,
        cantidad_dias integer NOT NULL,
        "DiasRetraso" integer NOT NULL DEFAULT 0,
        "Comentario" text,
        fecha_creacion timestamptz NOT NULL DEFAULT (now()),
        fecha_modificacion timestamptz,
        usuario_creacion text NOT NULL,
        usuario_modificacion text,
        "Estado" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_RentaDevolucion" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RentaDevolucion_Articulos_ArticuloId" FOREIGN KEY ("ArticuloId") REFERENCES "Articulos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RentaDevolucion_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RentaDevolucion_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_Articulos_GeneroId" ON "Articulos" ("GeneroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_Articulos_IdiomaId" ON "Articulos" ("IdiomaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_Articulos_TipoArticuloId" ON "Articulos" ("TipoArticuloId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Clientes_Cedula" ON "Clientes" ("Cedula");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_ElencoArticulo_ArticuloId" ON "ElencoArticulo" ("ArticuloId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_ElencoArticulo_ElencoId" ON "ElencoArticulo" ("ElencoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_ElencoArticulo_RolElencoId" ON "ElencoArticulo" ("RolElencoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Empleados_Cedula" ON "Empleados" ("Cedula");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Empleados_nombre_usuario" ON "Empleados" (nombre_usuario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_RentaDevolucion_ArticuloId" ON "RentaDevolucion" ("ArticuloId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_RentaDevolucion_ClienteId" ON "RentaDevolucion" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_RentaDevolucion_EmpleadoId" ON "RentaDevolucion" ("EmpleadoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE INDEX "IX_RentaDevolucion_fecha_renta" ON "RentaDevolucion" (fecha_renta);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_RentaDevolucion_NoRenta" ON "RentaDevolucion" ("NoRenta");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531034635_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260531034635_InitialCreate', '10.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601020524_AddTipoArticuloGenero') THEN
    CREATE TABLE "TiposArticulosGeneros" (
        "TipoArticuloId" bigint NOT NULL,
        "GeneroId" bigint NOT NULL,
        CONSTRAINT "PK_TiposArticulosGeneros" PRIMARY KEY ("TipoArticuloId", "GeneroId"),
        CONSTRAINT "FK_TiposArticulosGeneros_Generos_GeneroId" FOREIGN KEY ("GeneroId") REFERENCES "Generos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TiposArticulosGeneros_TiposArticulos_TipoArticuloId" FOREIGN KEY ("TipoArticuloId") REFERENCES "TiposArticulos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601020524_AddTipoArticuloGenero') THEN
    CREATE INDEX "IX_TiposArticulosGeneros_GeneroId" ON "TiposArticulosGeneros" ("GeneroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601020524_AddTipoArticuloGenero') THEN
    CREATE INDEX "IX_TiposArticulosGeneros_TipoArticuloId" ON "TiposArticulosGeneros" ("TipoArticuloId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601020524_AddTipoArticuloGenero') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260601020524_AddTipoArticuloGenero', '10.0.8');
    END IF;
END $EF$;
COMMIT;

